package(
    default_visibility = [
        "//visibility:public",
    ],
    features = ["-layering_check"],
)

py_library(
    name = "configure",
    srcs = ["configure.py"],
    deps = [
    ],
)
