package(
    default_visibility = [
        "//visibility:public",
    ],
    features = ["-layering_check"],
)

py_library(
    name = "bfm_load_data",
    srcs = ["bfm_load_data.py"],
    deps = [
    ],
)

py_library(
    name = "reconstruct_mesh",
    srcs = ["reconstruct_mesh.py"],
    deps = [
    ],
)

py_library(
    name = "bfm_visual",
    srcs = ["bfm_visual.py"],
    deps = [
    ],
)

py_library(
    name = "utils",
    srcs = ["utils.py"],
    deps = [
    ],
)